apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.pullSecret.name }}
  namespace: {{ .Values.namespace | quote  }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ .Values.auth.pullSecret.dockerconfigjson | quote }}
