apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace | quote  }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.secrets.values.DB_USERNAME | quote }}
  DB_PASSWORD: {{ .Values.secrets.values.DB_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secrets.values.JWT_SECRET | quote }}
  PEPPER: {{ .Values.secrets.values.PEPPER | quote }}
  RABBITMQ_USER: {{ .Values.secrets.values.RABBITMQ_USER | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.values.RABBITMQ_PASSWORD | quote }}
